#
# Copyright (c) 2013-2014, Marcus Rohrmoser mobile Software
# All rights reserved.
# 
# Redistribution and use in source and binary forms, with or without modification, are permitted
# provided that the following conditions are met:
# 
# 1. Redistributions of source code must retain the above copyright notice, this list of conditions
#    and the following disclaimer.
# 
# 2. The software must not be used for military or intelligence or related purposes nor
#    anything that's in conflict with human rights as declared in http://www.un.org/en/documents/udhr/ .
# 
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR
# IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND
# FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR
# CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
# DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
# DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER
# IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF
# THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
#
#
#
# Find episodes without relation to 'kommissar'
#
# Run:
#
# $ roqet episodes-without-kommissar.rq --results csv --input sparql --format rdfxml --data htdocs/episodes.rdf --data htdocs/kommissare.rdf
#
#
# http://www.w3.org/TR/rdf-sparql-query/#WritingSimpleQueries
#
# Install roqet (http://librdf.org/rasqal/roqet.html):
#
# $ brew install rasqal
# $ sudo apt-get install rasqal-utils
#
PREFIX dcterms: <http://purl.org/dc/terms/>
PREFIX dctype: <http://purl.org/dc/dcmitype/>
PREFIX owl: <http://www.w3.org/2002/07/owl#>

SELECT ?url_epi_year
WHERE {
  # just anything with a owl:sameAs
  ?url_epi_year
    owl:sameAs  ?url_epi .
  # narrow down to episodes
#  ?url_epi
#   a dctype:Text ;
#   dcterms:title ?title .
  # but without any relation to dcterms:hasPart
  OPTIONAL { ?url_komm dcterms:hasPart ?url_epi_year }  # http://www.w3.org/TR/rdf-sparql-query/#optionals
  FILTER ( !bound(?url_komm) )                          # http://www.w3.org/TR/rdf-sparql-query/#func-bound
 }
